package fi.kim.gui;

import fi.kim.pelaajat.Pelaaja;

/**
 *
 * @author sepkim
 */
public class Kayttoliittyma extends javax.swing.JFrame implements Runnable {
    /**
     * Ohjelman visuaalinen käyttöliittymä.
     */
    public Kayttoliittyma() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arvattavaSana = new javax.swing.JLabel();
        arvausKentta = new javax.swing.JTextField();
        arvausNappi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arvattavaSana.setText("jLabel1");

        arvausNappi.setText("Arvaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(arvattavaSana, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(arvausKentta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arvausNappi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arvattavaSana, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvausKentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvausNappi))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arvattavaSana;
    private javax.swing.JTextField arvausKentta;
    private javax.swing.JButton arvausNappi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        setVisible(true);
    }
    
    /**
     * Lisää ActionListenerin ArvausNapille.
     * @param pelaaja Pelaaja, jonka sanaa muokataan.
     */
    public void lisaaKuuntelija(Pelaaja pelaaja) {
        arvausNappi.addActionListener(new ArvausKuuntelija(arvausKentta, pelaaja, arvattavaSana));
    }
    
    /**
     * Metodi asettaa parametrina saaneeen merkkijonon arvattavaSana laatikkoon.
     * @param sana Merkkijono joka laitetaan laatikkoon.
     */
    public void setArvattavaSanaKentta(String sana) {
        arvattavaSana.setText(sana);
    }

}