package fi.kim.gui;

import fi.kim.pelaajat.Pelaaja;

/**
 *
 * @author sepkim
 */
public class Kayttoliittyma extends javax.swing.JFrame implements Runnable {
    /**
     * Ohjelman visuaalinen käyttöliittymä.
     */
    public Kayttoliittyma() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arvattavaSana = new javax.swing.JLabel();
        arvausKentta = new javax.swing.JTextField();
        arvausNappi = new javax.swing.JButton();
        vaariaArvauksia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arvattavaSana.setText("jLabel1");

        arvausNappi.setText("Arvaa");
        arvausNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvausNappiActionPerformed(evt);
            }
        });

        vaariaArvauksia.setText("0");

        jLabel1.setText("Vääriä arvauksia: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(arvattavaSana, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(arvausKentta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arvausNappi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(vaariaArvauksia)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaariaArvauksia)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arvattavaSana, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvausKentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvausNappi))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arvausNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvausNappiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arvausNappiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arvattavaSana;
    private javax.swing.JTextField arvausKentta;
    private javax.swing.JButton arvausNappi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel vaariaArvauksia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        setVisible(true);
    }
    
    /**
     * Lisää ActionListenerin ArvausNapille.
     * @param pelaaja Pelaaja, jonka sanaa muokataan.
     */
    public void lisaaKuuntelija(Pelaaja pelaaja) {
        arvausNappi.addActionListener(new ArvausKuuntelija(arvausKentta, pelaaja, arvattavaSana, vaariaArvauksia));
    }
    
    /**
     * Metodi asettaa parametrina saaneeen merkkijonon arvattavaSana laatikkoon.
     * @param sana Merkkijono joka laitetaan laatikkoon.
     */
    public void setArvattavaSanaKentta(String sana) {
        arvattavaSana.setText(sana);
    }
    
    public void setVaariaArvauksia(int luku) {
        vaariaArvauksia.setText(Integer.toString(luku));
    }

}